apiVersion: v1
kind: Pod
metadata:
  name: candy-service-pod
spec:
  serviceAccount: candy-svc
  securityContext:
    fsGroup: 2000
  containers:
  - name: candy-service
    image: linuxacademycontent/candy-service:1
    resources:
      requests:
        memory: "64Mi"
        cpu: "250mi"
      limits:
        memory: "128"
        cpu: "500mi"
     env:
     - name: DB_PASSWORD
       valueFrom:
         secretKeyRef:
           name: db-password
           key: password
     volumeMounts:
     - name: config-volume
       mountPath: /etc/candy-service/
   volumes:
   - name: config-volume
     configMap:
       name: candy-service-config
       
       
     
         
