apiVersion: v1
kind: Pod
metadata:
  name: candy-service-pod
spec:
  serviceAccount: candy-svc
  securityContext:
    fsGroup: 2000
  containers:
  - name: candy-service
    resources:
      requests:
        memory: "64Mi"
        cpu: "250mi"
      limits:
        memory: "128"
        cpu: "500mi"
     env:
     - name: DB_PASSWORD
       valueFrom:
         secretKeyRef:
           name: candy-service-secret
           key: db_password
     volumeMounts:
     - name: config-volume
       
       
     
         
